### ISSUE TITLE
Change in version 0.7 of Julia on the scalar+array operations

### ISSUE THREAD

**Issue by semmottos** [PaulSoderlind/JuliaTutorial#1]
Hi!
I'm going through your tutorial, nice piece of work. Thanks for that!

One observation. This document:
     https://github.com/JuliaLang/julia/blob/master/NEWS.md
titled:
     Julia v0.7.0 Release Notes
has this paragraph:
     Automatically broadcasted + and - for array + scalar, scalar - array, and so-on have been
     deprecated due to inconsistency with linear algebra. Use .+ and .- for these operations instead
     (#22880, #22932).

I think you should consider changing all these scalar-array operations to use the dotted notation because they seem to work already in 0.6.2 and especially because 0.7 should be available Real Soon Now.

Jussi Salmela

**Comment by PaulSoderlind** [comment]
Thanks for the kind feedback. 
I believe that I have fixed all scalar .+ arrays cases already, but maybe I missed a few. Do you have any particular one in mind?
/Paul S

**Comment by semmottos** [comment]
I'm sorry to have bothered you for nothing. I had misunderstood what operators were involved in the deprecation changes mentioned above. I thought that multiplication of arrays with scalars was included also.

I should have understood that this can't be true because the examples in your guide have examples of both .+ and * following each other closely and enhanced with your remark of noticing the dot. Sorry!

I have still something to you, though these are just misprints not having to do with the subject matter and thus not disturbing the understanding of the reader.

##### Tutorial_01_Basics.ipynb

In the 'Load Packages' section:

1.
The line
	Once a package is installed (the most common once are already ...
should be
	Once a package is installed (the most common ones are already ...

2.
Calulations with Mixed Types ==> Calculations with Mixed Types

3.
In 'Arrays of Arrays (or other types)':

You can store very different things (a mixture of numers, ...
You can store very different things (a mixture of numbers, ...

Jussi

**Comment by PaulSoderlind** [comment]
Thanks. I'll fix those things. /Paul
